# Generated by Django 5.0.4 on 2024-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=7064322335, max_length=12),
            preserve_default=False,
        ),
    ]
